version: "3.8"

services:
  milvus-standalone:
    image: milvusdb/milvus:v2.4.0
    container_name: milvus-standalone
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - ./data/milvus:/var/lib/milvus

  ai-webapp:
    build: .
    container_name: ai-webapp
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - MILVUS_URL=${MILVUS_URL}
    depends_on:
      - milvus-standalone
    volumes:
      - ./pdfs:/app/pdfs
      - ./logs:/app/logs
      - ./data/sqlite:/app/data/sqlite